/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllPanels;

/**
 *
 * @author skerd
 */
public class congratulationPanel extends javax.swing.JPanel {

    /**
     * Creates new form congratulationPanel
    
   */
    
    private int nrOfMoves;
    private String whereToGo;
    
    public congratulationPanel( String whereToGo , int moves) {
        
        nrOfMoves = moves;
        this.whereToGo = whereToGo;
        initComponents();
        
        completedLabel.setText("You competed the puzzle in " + nrOfMoves + " moves!!!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        completedLabel = new javax.swing.JLabel();
        mainMenuBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        gameModeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Congratulations!");

        completedLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        completedLabel.setForeground(new java.awt.Color(0, 0, 0));
        completedLabel.setText("You competed the puzzle!!!!");

        mainMenuBtn.setBackground(new java.awt.Color(255, 255, 153));
        mainMenuBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        nextBtn.setBackground(new java.awt.Color(255, 255, 153));
        nextBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        gameModeBtn.setBackground(new java.awt.Color(255, 255, 153));
        gameModeBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        gameModeBtn.setForeground(new java.awt.Color(255, 255, 255));
        gameModeBtn.setText("Game Modes");
        gameModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameModeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(completedLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completedLabel)
                .addGap(66, 66, 66)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(gameModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed

        cs319.main.window.getContentPane().removeAll();

        mainMenu mainMenu = new mainMenu();
        cs319.main.window.add(mainMenu);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();

        System.out.println("Opening options menu");

    }//GEN-LAST:event_mainMenuBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
       
        cs319.main.window.getContentPane().removeAll();

        if( whereToGo.equals("NormalLevel") || whereToGo.equals("DiamondLevel")){
            
            selectLevelPanel newGame = new selectLevelPanel();
            cs319.main.window.add(newGame);
            
        }
        else if( whereToGo.equals("Stories")){
            allStorisPanel newGame = new allStorisPanel();
            cs319.main.window.add(newGame);
        }
       
        cs319.main.window.revalidate();
        cs319.main.window.repaint();
        
        
    }//GEN-LAST:event_nextBtnActionPerformed

    private void gameModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameModeBtnActionPerformed
       cs319.main.window.getContentPane().removeAll();

        newGamePanel newGame = new newGamePanel();
        cs319.main.window.add(newGame);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();
    }//GEN-LAST:event_gameModeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completedLabel;
    private javax.swing.JButton gameModeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
