/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllPanels;

import javax.swing.ImageIcon;

/**
 *
 * @author skerd
 */
public class creditsPanel extends javax.swing.JPanel {

    /**
     * Creates new form creditsPanel
     */
    public creditsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        groupId = new javax.swing.JLabel();
        kaan = new javax.swing.JLabel();
        umair = new javax.swing.JLabel();
        vandana = new javax.swing.JLabel();
        skerd = new javax.swing.JLabel();
        burak = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("IQ Puzzler Pro Team");

        groupId.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        groupId.setForeground(new java.awt.Color(0, 0, 0));
        groupId.setText("Group: 2G - Cs319");

        kaan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        kaan.setForeground(new java.awt.Color(0, 0, 0));
        kaan.setText("Kaan Altınay");

        umair.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        umair.setForeground(new java.awt.Color(0, 0, 0));
        umair.setText("Muhammed Umair Ahmed");

        vandana.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        vandana.setForeground(new java.awt.Color(0, 0, 0));
        vandana.setText("Aliyu Saifullah Vandana");

        skerd.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        skerd.setForeground(new java.awt.Color(0, 0, 0));
        skerd.setText("Skerd Xhafa");

        burak.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        burak.setForeground(new java.awt.Color(0, 0, 0));
        burak.setText("Burak Alaydın");

        ImageIcon icooon = new ImageIcon("Pictures/logo2.jpg");

        logoLabel.setIcon(icooon);

        backBtn.setBackground(new java.awt.Color(255, 255, 153));
        backBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(groupId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(umair)
                            .addComponent(vandana)
                            .addComponent(burak)
                            .addComponent(kaan)
                            .addComponent(skerd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(427, 427, 427))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(groupId)
                        .addGap(12, 12, 12)
                        .addComponent(kaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skerd)
                        .addGap(7, 7, 7)
                        .addComponent(umair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vandana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(burak)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)))
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cs319.main.window.getContentPane().removeAll();
        
        mainMenu menu = new mainMenu();
        cs319.main.window.add(menu);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();
        
        System.out.println("Going back to mainn menu");
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel burak;
    private javax.swing.JLabel groupId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kaan;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel skerd;
    private javax.swing.JLabel umair;
    private javax.swing.JLabel vandana;
    // End of variables declaration//GEN-END:variables
}
