/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllPanels;

import Generated.allGamesPanelHere;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author skerd
 */
public class pausePanel extends javax.swing.JPanel {

    /**
     * Creates new form pausePanel
     */
    
    private int tileType;
    
    public pausePanel(int tileType) {
        initComponents();
        
        this.tileType = tileType;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resumeBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gameModeBtn = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        saveGame1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        resumeBtn.setBackground(new java.awt.Color(255, 255, 153));
        resumeBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resumeBtn.setForeground(new java.awt.Color(255, 255, 255));
        resumeBtn.setText("Resume");
        resumeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setBackground(new java.awt.Color(255, 255, 153));
        mainMenuBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Pause Menu");

        gameModeBtn.setBackground(new java.awt.Color(255, 255, 153));
        gameModeBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        gameModeBtn.setForeground(new java.awt.Color(255, 255, 255));
        gameModeBtn.setText("Game Modes");
        gameModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameModeBtnActionPerformed(evt);
            }
        });

        ImageIcon icooon = new ImageIcon("Pictures/logo2.jpg");

        logoLabel.setIcon(icooon);

        saveGame1.setBackground(new java.awt.Color(255, 255, 153));
        saveGame1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        saveGame1.setForeground(new java.awt.Color(255, 255, 255));
        saveGame1.setText("SaveGame");
        saveGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGame1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(469, 469, 469))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gameModeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resumeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(520, 520, 520))))
            .addGroup(layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(resumeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveGame1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(gameModeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuBtn)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gameModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameModeBtnActionPerformed
        cs319.main.window.getContentPane().removeAll();

        newGamePanel newGame = new newGamePanel();
        cs319.main.window.add(newGame);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();
    }//GEN-LAST:event_gameModeBtnActionPerformed

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed

        cs319.main.window.getContentPane().removeAll();

        mainMenu mainMenu = new mainMenu();
        cs319.main.window.add(mainMenu);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();

        System.out.println("Opening options menu");
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    private void resumeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeBtnActionPerformed

       allGamesPanelHere.counter.pauseTime();
                        
        System.out.println("Resume Btn !@@@@@@@@@@@@@@@@@@@");
        allGamesPanelHere.changeMiddle();

        cs319.main.window.revalidate();
        cs319.main.window.repaint();

        System.out.println("Opening options menu");
    }//GEN-LAST:event_resumeBtnActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
       int keyCode = evt.getKeyCode();
       
       if (keyCode == KeyEvent.VK_ESCAPE) {

            allGamesPanelHere.counter.pauseTime();

            System.out.println("Escape !@@@@@@@@@@@@@@@@@@@");
            allGamesPanelHere.changeMiddle();

            cs319.main.window.revalidate();
            cs319.main.window.repaint();

        }
       
    }//GEN-LAST:event_formKeyReleased

    private void saveGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGame1ActionPerformed
        
        String savedOn = Generated.Board.saveGame(this.tileType);
        
        JFrame frame = new JFrame();
        Object[] options = {"Ok!"};
        int n = JOptionPane.showOptionDialog(frame,
            "Game Saved Successfully: " + savedOn,
            "Game Saved",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,     //do not use a custom Icon
            options,  //the titles of buttons
            options[0]); //default button title

        System.out.println(n);
        
        
        
    }//GEN-LAST:event_saveGame1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gameModeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton resumeBtn;
    private javax.swing.JButton saveGame1;
    // End of variables declaration//GEN-END:variables
}
