/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllPanels;

import Generated.allGamesPanelHere;
import Mechanics.GenerateRandom;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author skerd
 */
public class randomPanel extends javax.swing.JPanel {

    /**
     * Creates new form randomPanel
     */
    
    private int diffLevel = 1;
    
    public randomPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        playRandomBtn = new javax.swing.JButton();
        diffLabel = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        increaseBtn = new javax.swing.JButton();
        decreaseBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));
        setForeground(new java.awt.Color(255, 255, 0));

        ImageIcon icooon = new ImageIcon("Pictures/logo2.jpg");

        logoLabel.setIcon(icooon);

        playRandomBtn.setBackground(new java.awt.Color(255, 255, 153));
        playRandomBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        playRandomBtn.setForeground(new java.awt.Color(255, 255, 255));
        playRandomBtn.setText("Start Game");
        playRandomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playRandomBtnActionPerformed(evt);
            }
        });

        diffLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        diffLabel.setForeground(new java.awt.Color(0, 0, 0));
        diffLabel.setText("Difficulty: " + diffLevel
        );

        backBtn1.setBackground(new java.awt.Color(255, 255, 153));
        backBtn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backBtn1.setForeground(new java.awt.Color(255, 255, 255));
        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        increaseBtn.setBackground(new java.awt.Color(255, 255, 153));
        increaseBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        increaseBtn.setForeground(new java.awt.Color(255, 255, 255));
        increaseBtn.setText("+");
        increaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseBtnActionPerformed(evt);
            }
        });

        decreaseBtn.setBackground(new java.awt.Color(255, 255, 153));
        decreaseBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        decreaseBtn.setForeground(new java.awt.Color(255, 255, 255));
        decreaseBtn.setText("-");
        decreaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playRandomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(decreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(increaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 467, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(increaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(playRandomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playRandomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playRandomBtnActionPerformed
        // TODO add your handling code here:
        cs319.main.window.getContentPane().removeAll();

        int fileCount = new File("Levels\\Generated").listFiles().length;
        
        String levelGene = "Gene" + (fileCount+1);
        
        System.out.println("Generated: !!!!!!!!11   " + levelGene);
        
        GenerateRandom newGene = new GenerateRandom(11,5,levelGene);
        
        allGamesPanelHere randomGame= new allGamesPanelHere(11,5,0,"Generated", levelGene);
        cs319.main.window.add(randomGame);              
        cs319.main.window.revalidate();
        cs319.main.window.repaint();

        System.out.println("Going back to main menu");
    }//GEN-LAST:event_playRandomBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        
        cs319.main.window.getContentPane().removeAll();

        newGamePanel newGame = new newGamePanel();
        cs319.main.window.add(newGame);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();

        System.out.println("Going back to main menu");
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void increaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseBtnActionPerformed
        if( diffLevel <10){
            diffLevel++;
        }
        
        diffLabel.setText("Difficulty: " + diffLevel);
        
        this.repaint();
    }//GEN-LAST:event_increaseBtnActionPerformed

    private void decreaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseBtnActionPerformed
        
        if( diffLevel > 0){
            diffLevel--;
        }
        
        diffLabel.setText("Difficulty: " + diffLevel);
        
        this.repaint();
    }//GEN-LAST:event_decreaseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton decreaseBtn;
    private javax.swing.JLabel diffLabel;
    private javax.swing.JButton increaseBtn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton playRandomBtn;
    // End of variables declaration//GEN-END:variables
}
