/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllPanels;

import Generated.Board;

/**
 *
 * @author skerd
 */
public class timeIsUp extends javax.swing.JPanel {

    /**
     * Creates new form timeIsUp
     */
    public timeIsUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        completedLabel = new javax.swing.JLabel();
        mainMenuBtn = new javax.swing.JButton();
        replayBtn = new javax.swing.JButton();
        gameModeBtn = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sorry, time is up! :(");

        completedLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        completedLabel.setForeground(new java.awt.Color(0, 0, 0));
        completedLabel.setText("Puzzle was not completed withing the given time..");

        mainMenuBtn.setBackground(new java.awt.Color(255, 255, 153));
        mainMenuBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        replayBtn.setBackground(new java.awt.Color(255, 255, 153));
        replayBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        replayBtn.setForeground(new java.awt.Color(255, 255, 255));
        replayBtn.setText("Replay");
        replayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replayBtnActionPerformed(evt);
            }
        });

        gameModeBtn.setBackground(new java.awt.Color(255, 255, 153));
        gameModeBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        gameModeBtn.setForeground(new java.awt.Color(255, 255, 255));
        gameModeBtn.setText("Game Modes");
        gameModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameModeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completedLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addGap(436, 436, 436))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(449, 449, 449)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(replayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gameModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(455, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completedLabel)
                .addContainerGap(466, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(328, 328, 328)
                    .addComponent(replayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(gameModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed

        cs319.main.window.getContentPane().removeAll();

        mainMenu mainMenu = new mainMenu();
        cs319.main.window.add(mainMenu);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();

        System.out.println("Opening options menu");
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    private void replayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replayBtnActionPerformed

        cs319.main.window.getContentPane().removeAll();
                   
        Generated.allGamesPanelHere game = null;  
        game = new Generated.allGamesPanelHere(Board.boardWidth,Board.boardHeight,Board.TileType,Board.gameMode ,Board.level );

        cs319.main.window.add(game);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();

    }//GEN-LAST:event_replayBtnActionPerformed

    private void gameModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameModeBtnActionPerformed
        cs319.main.window.getContentPane().removeAll();

        newGamePanel newGame = new newGamePanel();
        cs319.main.window.add(newGame);
        cs319.main.window.revalidate();
        cs319.main.window.repaint();
    }//GEN-LAST:event_gameModeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completedLabel;
    private javax.swing.JButton gameModeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton replayBtn;
    // End of variables declaration//GEN-END:variables
}
